[project]
title = "WeatherPlay"
version = "0.1.0"
port = 8501
slug = "weatherplay"  
entrypoint = "hello.py"    

[branding]
name = "WeatherPlay"
logo = "images/logo.png"
favicon = "images/Weather-Tornado-icon.png"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/weather.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"